# Copyright (C) 2022 Explore.dev, Unipessoal Lda - All Rights Reserved
# Use of this source code is governed by a license that can be
# found in the LICENSE file

version: "3"

tasks:
  format:
    summary: |
      Formats Go files.

      Run with --watch or -w to watch for changes on Go files.
    cmds:
      - gofmt -s -w .
    sources:
      - ./**/*.go

  build:
    deps:
      - build-cli
      - build-aladino-parser
    summary: |
      Builds Go files.

      Run with --watch or -w to watch for changes on Go files.
    cmds:
      # We are using -buildmode=pie to avoid the following error on MacOS:
      # ld: warning: -no_pie is deprecated when targeting new OS versions
      - go build -buildmode=pie
    sources:
      - ./**/*.go

  build-aladino-parser:
    summary: |
      Generates Aladino parser written in Go.

      Run with --watch or -w to watch for changes on yacc file.
    cmds:
      # For debug purposes, remove the -l argumment enabling the line directives in parser.go.
      - goyacc -l -o lang/aladino/parser.go -p Aladino lang/aladino/parser.y
    sources:
      - lang/aladino/parser.y
    generates:
      - lang/aladino/parser.go

  build-cli:
    summary: |
      Builds commands.

      Run with --watch or -w to watch for changes on Go files.
    cmds:
      - go build -buildmode=pie -o reviewpad-cli ./cli/main.go
    sources:
      - ./cli/**/*.go

  test:
    summary: |
      Runs unit tests with coverage

      Run with --watch or -w to watch for changes on _test.go files.
    cmds:
      - gotestsum -- -buildmode=pie -coverprofile=coverage.out ./...
      - . scripts/exclude-from-code-coverage.sh
    sources:
      - ./**/*_test.go

  coverage:
    summary: Generates coverage report and opens it
    deps:
      - test
    cmds:
      - go tool cover -html=coverage.out

  coverage-diff:
    summary: Show coverage difference between current branch and master
    cmds:
      - |
        gotestsum -- -coverprofile=coverage.out ./...
        . scripts/exclude-from-code-coverage.sh
        current_branch=$(git rev-parse --abbrev-ref HEAD)

        current_line_total=$(go tool cover -func coverage.out | grep -e 'total:')
        current_total_int=$(echo "$current_line_total" | grep -o '[0-9.]*')
        git checkout main
        gotestsum -- -coverprofile=coverage.out ./...
        . scripts/exclude-from-code-coverage.sh

        main_line_total=$(go tool cover -func coverage.out | grep -e 'total:')
        main_total_int=$(echo "$main_line_total" | grep -o '[0-9.]*')
        git checkout $current_branch
        echo "branch $current_branch coverage: $current_total_int%"
        echo "branch main coverage: $main_total_int%"
        if ((current_total_int > main_total_int))
        then
          diff=$(echo "$current_total_int $main_total_int" | awk '{print $1 - $2}')
          echo "difference: + $diff%"
        else
          diff=$(echo "$main_total_int $current_total_int" | awk '{print $1 - $2}')
          echo "difference: - $diff%"
        fi
    silent: true

  lint:
    summary: |
      Runs the linter
      If error try `brew install golangci-lint`
    cmds:
      - golangci-lint run

  check:
    deps:
      - format
      - build
      - test
      - lint
