package main

const defaultEvent = `{
  "event_name": "workflow_run",
  "event": {
    "action": "completed",
    "organization": {
      "avatar_url": "https://avatars.githubusercontent.com/u/77885052?v=4",
      "description": "Supercharged pull requests - Ship faster with higher quality!",
      "events_url": "https://api.github.com/orgs/reviewpad/events",
      "hooks_url": "https://api.github.com/orgs/reviewpad/hooks",
      "id": 77885052,
      "issues_url": "https://api.github.com/orgs/reviewpad/issues",
      "login": "reviewpad",
      "members_url": "https://api.github.com/orgs/reviewpad/members{/member}",
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjc3ODg1MDUy",
      "public_members_url": "https://api.github.com/orgs/reviewpad/public_members{/member}",
      "repos_url": "https://api.github.com/orgs/reviewpad/repos",
      "url": "https://api.github.com/orgs/reviewpad"
    },
    "repository": {
      "allow_forking": true,
      "archive_url": "https://api.github.com/repos/reviewpad/reviewpad/{archive_format}{/ref}",
      "archived": false,
      "assignees_url": "https://api.github.com/repos/reviewpad/reviewpad/assignees{/user}",
      "blobs_url": "https://api.github.com/repos/reviewpad/reviewpad/git/blobs{/sha}",
      "branches_url": "https://api.github.com/repos/reviewpad/reviewpad/branches{/branch}",
      "clone_url": "https://github.com/reviewpad/reviewpad.git",
      "collaborators_url": "https://api.github.com/repos/reviewpad/reviewpad/collaborators{/collaborator}",
      "comments_url": "https://api.github.com/repos/reviewpad/reviewpad/comments{/number}",
      "commits_url": "https://api.github.com/repos/reviewpad/reviewpad/commits{/sha}",
      "compare_url": "https://api.github.com/repos/reviewpad/reviewpad/compare/{base}...{head}",
      "contents_url": "https://api.github.com/repos/reviewpad/reviewpad/contents/{+path}",
      "contributors_url": "https://api.github.com/repos/reviewpad/reviewpad/contributors",
      "created_at": "2022-05-27T09:21:44Z",
      "default_branch": "main",
      "deployments_url": "https://api.github.com/repos/reviewpad/reviewpad/deployments",
      "description": "Supercharged pull requests!",
      "disabled": false,
      "downloads_url": "https://api.github.com/repos/reviewpad/reviewpad/downloads",
      "events_url": "https://api.github.com/repos/reviewpad/reviewpad/events",
      "fork": false,
      "forks": 6,
      "forks_count": 6,
      "forks_url": "https://api.github.com/repos/reviewpad/reviewpad/forks",
      "full_name": "reviewpad/reviewpad",
      "git_commits_url": "https://api.github.com/repos/reviewpad/reviewpad/git/commits{/sha}",
      "git_refs_url": "https://api.github.com/repos/reviewpad/reviewpad/git/refs{/sha}",
      "git_tags_url": "https://api.github.com/repos/reviewpad/reviewpad/git/tags{/sha}",
      "git_url": "git://github.com/reviewpad/reviewpad.git",
      "has_downloads": true,
      "has_issues": true,
      "has_pages": false,
      "has_projects": true,
      "has_wiki": true,
      "homepage": "https://docs.reviewpad.com",
      "hooks_url": "https://api.github.com/repos/reviewpad/reviewpad/hooks",
      "html_url": "https://github.com/reviewpad/reviewpad",
      "id": 496935038,
      "is_template": false,
      "issue_comment_url": "https://api.github.com/repos/reviewpad/reviewpad/issues/comments{/number}",
      "issue_events_url": "https://api.github.com/repos/reviewpad/reviewpad/issues/events{/number}",
      "issues_url": "https://api.github.com/repos/reviewpad/reviewpad/issues{/number}",
      "keys_url": "https://api.github.com/repos/reviewpad/reviewpad/keys{/key_id}",
      "labels_url": "https://api.github.com/repos/reviewpad/reviewpad/labels{/name}",
      "language": "Go",
      "languages_url": "https://api.github.com/repos/reviewpad/reviewpad/languages",
      "license": {
        "key": "lgpl-3.0",
        "name": "GNU Lesser General Public License v3.0",
        "node_id": "MDc6TGljZW5zZTEy",
        "spdx_id": "LGPL-3.0",
        "url": "https://api.github.com/licenses/lgpl-3.0"
      },
      "merges_url": "https://api.github.com/repos/reviewpad/reviewpad/merges",
      "milestones_url": "https://api.github.com/repos/reviewpad/reviewpad/milestones{/number}",
      "mirror_url": null,
      "name": "reviewpad",
      "node_id": "R_kgDOHZ6gfg",
      "notifications_url": "https://api.github.com/repos/reviewpad/reviewpad/notifications{?since,all,participating}",
      "open_issues": 25,
      "open_issues_count": 25,
      "owner": {
        "avatar_url": "https://avatars.githubusercontent.com/u/77885052?v=4",
        "events_url": "https://api.github.com/users/reviewpad/events{/privacy}",
        "followers_url": "https://api.github.com/users/reviewpad/followers",
        "following_url": "https://api.github.com/users/reviewpad/following{/other_user}",
        "gists_url": "https://api.github.com/users/reviewpad/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/reviewpad",
        "id": 77885052,
        "login": "reviewpad",
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjc3ODg1MDUy",
        "organizations_url": "https://api.github.com/users/reviewpad/orgs",
        "received_events_url": "https://api.github.com/users/reviewpad/received_events",
        "repos_url": "https://api.github.com/users/reviewpad/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/reviewpad/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/reviewpad/subscriptions",
        "type": "Organization",
        "url": "https://api.github.com/users/reviewpad"
      },
      "private": false,
      "pulls_url": "https://api.github.com/repos/reviewpad/reviewpad/pulls{/number}",
      "pushed_at": "2022-07-20T15:22:00Z",
      "releases_url": "https://api.github.com/repos/reviewpad/reviewpad/releases{/id}",
      "size": 308,
      "ssh_url": "git@github.com:reviewpad/reviewpad.git",
      "stargazers_count": 31,
      "stargazers_url": "https://api.github.com/repos/reviewpad/reviewpad/stargazers",
      "statuses_url": "https://api.github.com/repos/reviewpad/reviewpad/statuses/{sha}",
      "subscribers_url": "https://api.github.com/repos/reviewpad/reviewpad/subscribers",
      "subscription_url": "https://api.github.com/repos/reviewpad/reviewpad/subscription",
      "svn_url": "https://github.com/reviewpad/reviewpad",
      "tags_url": "https://api.github.com/repos/reviewpad/reviewpad/tags",
      "teams_url": "https://api.github.com/repos/reviewpad/reviewpad/teams",
      "topics": [
        "automation-framework",
        "github",
        "golang",
        "pull-request-review",
        "pull-requests"
      ],
      "trees_url": "https://api.github.com/repos/reviewpad/reviewpad/git/trees{/sha}",
      "updated_at": "2022-07-14T10:42:18Z",
      "url": "https://api.github.com/repos/reviewpad/reviewpad",
      "visibility": "public",
      "watchers": 31,
      "watchers_count": 31,
      "web_commit_signoff_required": false
    },
    "sender": {
      "avatar_url": "https://avatars.githubusercontent.com/u/601882?v=4",
      "events_url": "https://api.github.com/users/marcelosousa/events{/privacy}",
      "followers_url": "https://api.github.com/users/marcelosousa/followers",
      "following_url": "https://api.github.com/users/marcelosousa/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcelosousa/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/marcelosousa",
      "id": 601882,
      "login": "marcelosousa",
      "node_id": "MDQ6VXNlcjYwMTg4Mg==",
      "organizations_url": "https://api.github.com/users/marcelosousa/orgs",
      "received_events_url": "https://api.github.com/users/marcelosousa/received_events",
      "repos_url": "https://api.github.com/users/marcelosousa/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/marcelosousa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcelosousa/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/marcelosousa"
    },
    "workflow": {
      "badge_url": "https://github.com/reviewpad/reviewpad/workflows/Pull%20Request%20Build/badge.svg",
      "created_at": "2022-07-07T11:17:47.000Z",
      "html_url": "https://github.com/reviewpad/reviewpad/blob/main/.github/workflows/pull_request_build.yml",
      "id": 29778599,
      "name": "Pull Request Build",
      "node_id": "W_kwDOHZ6gfs4BxmKn",
      "path": ".github/workflows/pull_request_build.yml",
      "state": "active",
      "updated_at": "2022-07-07T11:17:47.000Z",
      "url": "https://api.github.com/repos/reviewpad/reviewpad/actions/workflows/29778599"
    },
    "workflow_run": {
      "actor": {
        "avatar_url": "https://avatars.githubusercontent.com/u/601882?v=4",
        "events_url": "https://api.github.com/users/marcelosousa/events{/privacy}",
        "followers_url": "https://api.github.com/users/marcelosousa/followers",
        "following_url": "https://api.github.com/users/marcelosousa/following{/other_user}",
        "gists_url": "https://api.github.com/users/marcelosousa/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/marcelosousa",
        "id": 601882,
        "login": "marcelosousa",
        "node_id": "MDQ6VXNlcjYwMTg4Mg==",
        "organizations_url": "https://api.github.com/users/marcelosousa/orgs",
        "received_events_url": "https://api.github.com/users/marcelosousa/received_events",
        "repos_url": "https://api.github.com/users/marcelosousa/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/marcelosousa/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marcelosousa/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/marcelosousa"
      },
      "artifacts_url": "https://api.github.com/repos/reviewpad/reviewpad/actions/runs/2705801670/artifacts",
      "cancel_url": "https://api.github.com/repos/reviewpad/reviewpad/actions/runs/2705801670/cancel",
      "check_suite_id": 7442918866,
      "check_suite_node_id": "CS_kwDOHZ6gfs8AAAABu6Ht0g",
      "check_suite_url": "https://api.github.com/repos/reviewpad/reviewpad/check-suites/7442918866",
      "conclusion": "success",
      "created_at": "2022-07-20T15:22:02Z",
      "event": "pull_request",
      "head_branch": "v3.x",
      "head_commit": {
        "author": {
          "email": "601882+marcelosousa@users.noreply.github.com",
          "name": "marcelosousa"
        },
        "committer": {
          "email": "601882+marcelosousa@users.noreply.github.com",
          "name": "marcelosousa"
        },
        "id": "41632330e2d328bfc8d1d0b59f0bbdf351f828bd",
        "message": "style: improve unit tests names",
        "timestamp": "2022-07-20T15:21:55Z",
        "tree_id": "c1da364eea0f8ea351265e4ee242bdaf8b18339f"
      },
      "head_repository": {
        "archive_url": "https://api.github.com/repos/reviewpad/reviewpad/{archive_format}{/ref}",
        "assignees_url": "https://api.github.com/repos/reviewpad/reviewpad/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/reviewpad/reviewpad/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/reviewpad/reviewpad/branches{/branch}",
        "collaborators_url": "https://api.github.com/repos/reviewpad/reviewpad/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/reviewpad/reviewpad/comments{/number}",
        "commits_url": "https://api.github.com/repos/reviewpad/reviewpad/commits{/sha}",
        "compare_url": "https://api.github.com/repos/reviewpad/reviewpad/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/reviewpad/reviewpad/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/reviewpad/reviewpad/contributors",
        "deployments_url": "https://api.github.com/repos/reviewpad/reviewpad/deployments",
        "description": "Supercharged pull requests!",
        "downloads_url": "https://api.github.com/repos/reviewpad/reviewpad/downloads",
        "events_url": "https://api.github.com/repos/reviewpad/reviewpad/events",
        "fork": false,
        "forks_url": "https://api.github.com/repos/reviewpad/reviewpad/forks",
        "full_name": "reviewpad/reviewpad",
        "git_commits_url": "https://api.github.com/repos/reviewpad/reviewpad/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/reviewpad/reviewpad/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/reviewpad/reviewpad/git/tags{/sha}",
        "hooks_url": "https://api.github.com/repos/reviewpad/reviewpad/hooks",
        "html_url": "https://github.com/reviewpad/reviewpad",
        "id": 496935038,
        "issue_comment_url": "https://api.github.com/repos/reviewpad/reviewpad/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/reviewpad/reviewpad/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/reviewpad/reviewpad/issues{/number}",
        "keys_url": "https://api.github.com/repos/reviewpad/reviewpad/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/reviewpad/reviewpad/labels{/name}",
        "languages_url": "https://api.github.com/repos/reviewpad/reviewpad/languages",
        "merges_url": "https://api.github.com/repos/reviewpad/reviewpad/merges",
        "milestones_url": "https://api.github.com/repos/reviewpad/reviewpad/milestones{/number}",
        "name": "reviewpad",
        "node_id": "R_kgDOHZ6gfg",
        "notifications_url": "https://api.github.com/repos/reviewpad/reviewpad/notifications{?since,all,participating}",
        "owner": {
          "avatar_url": "https://avatars.githubusercontent.com/u/77885052?v=4",
          "events_url": "https://api.github.com/users/reviewpad/events{/privacy}",
          "followers_url": "https://api.github.com/users/reviewpad/followers",
          "following_url": "https://api.github.com/users/reviewpad/following{/other_user}",
          "gists_url": "https://api.github.com/users/reviewpad/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/reviewpad",
          "id": 77885052,
          "login": "reviewpad",
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjc3ODg1MDUy",
          "organizations_url": "https://api.github.com/users/reviewpad/orgs",
          "received_events_url": "https://api.github.com/users/reviewpad/received_events",
          "repos_url": "https://api.github.com/users/reviewpad/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/reviewpad/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/reviewpad/subscriptions",
          "type": "Organization",
          "url": "https://api.github.com/users/reviewpad"
        },
        "private": false,
        "pulls_url": "https://api.github.com/repos/reviewpad/reviewpad/pulls{/number}",
        "releases_url": "https://api.github.com/repos/reviewpad/reviewpad/releases{/id}",
        "stargazers_url": "https://api.github.com/repos/reviewpad/reviewpad/stargazers",
        "statuses_url": "https://api.github.com/repos/reviewpad/reviewpad/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/reviewpad/reviewpad/subscribers",
        "subscription_url": "https://api.github.com/repos/reviewpad/reviewpad/subscription",
        "tags_url": "https://api.github.com/repos/reviewpad/reviewpad/tags",
        "teams_url": "https://api.github.com/repos/reviewpad/reviewpad/teams",
        "trees_url": "https://api.github.com/repos/reviewpad/reviewpad/git/trees{/sha}",
        "url": "https://api.github.com/repos/reviewpad/reviewpad"
      },
      "head_sha": "41632330e2d328bfc8d1d0b59f0bbdf351f828bd",
      "html_url": "https://github.com/reviewpad/reviewpad/actions/runs/2705801670",
      "id": 2705801670,
      "jobs_url": "https://api.github.com/repos/reviewpad/reviewpad/actions/runs/2705801670/jobs",
      "logs_url": "https://api.github.com/repos/reviewpad/reviewpad/actions/runs/2705801670/logs",
      "name": "Pull Request Build",
      "node_id": "WFR_kwLOHZ6gfs6hR0HG",
      "path": ".github/workflows/pull_request_build.yml",
      "previous_attempt_url": null,
      "pull_requests": [
        {
          "base": {
            "ref": "main",
            "repo": {
              "id": 496935038,
              "name": "reviewpad",
              "url": "https://api.github.com/repos/reviewpad/reviewpad"
            },
            "sha": "17850d3e3d0805342f5e8a3abfe58d95815d6277"
          },
          "head": {
            "ref": "v3.x",
            "repo": {
              "id": 496935038,
              "name": "reviewpad",
              "url": "https://api.github.com/repos/reviewpad/reviewpad"
            },
            "sha": "41632330e2d328bfc8d1d0b59f0bbdf351f828bd"
          },
          "id": 1001032622,
          "number": 150,
          "url": "https://api.github.com/repos/reviewpad/reviewpad/pulls/150"
        }
      ],
      "referenced_workflows": [],
      "repository": {
        "archive_url": "https://api.github.com/repos/reviewpad/reviewpad/{archive_format}{/ref}",
        "assignees_url": "https://api.github.com/repos/reviewpad/reviewpad/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/reviewpad/reviewpad/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/reviewpad/reviewpad/branches{/branch}",
        "collaborators_url": "https://api.github.com/repos/reviewpad/reviewpad/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/reviewpad/reviewpad/comments{/number}",
        "commits_url": "https://api.github.com/repos/reviewpad/reviewpad/commits{/sha}",
        "compare_url": "https://api.github.com/repos/reviewpad/reviewpad/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/reviewpad/reviewpad/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/reviewpad/reviewpad/contributors",
        "deployments_url": "https://api.github.com/repos/reviewpad/reviewpad/deployments",
        "description": "Supercharged pull requests!",
        "downloads_url": "https://api.github.com/repos/reviewpad/reviewpad/downloads",
        "events_url": "https://api.github.com/repos/reviewpad/reviewpad/events",
        "fork": false,
        "forks_url": "https://api.github.com/repos/reviewpad/reviewpad/forks",
        "full_name": "reviewpad/reviewpad",
        "git_commits_url": "https://api.github.com/repos/reviewpad/reviewpad/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/reviewpad/reviewpad/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/reviewpad/reviewpad/git/tags{/sha}",
        "hooks_url": "https://api.github.com/repos/reviewpad/reviewpad/hooks",
        "html_url": "https://github.com/reviewpad/reviewpad",
        "id": 496935038,
        "issue_comment_url": "https://api.github.com/repos/reviewpad/reviewpad/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/reviewpad/reviewpad/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/reviewpad/reviewpad/issues{/number}",
        "keys_url": "https://api.github.com/repos/reviewpad/reviewpad/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/reviewpad/reviewpad/labels{/name}",
        "languages_url": "https://api.github.com/repos/reviewpad/reviewpad/languages",
        "merges_url": "https://api.github.com/repos/reviewpad/reviewpad/merges",
        "milestones_url": "https://api.github.com/repos/reviewpad/reviewpad/milestones{/number}",
        "name": "reviewpad",
        "node_id": "R_kgDOHZ6gfg",
        "notifications_url": "https://api.github.com/repos/reviewpad/reviewpad/notifications{?since,all,participating}",
        "owner": {
          "avatar_url": "https://avatars.githubusercontent.com/u/77885052?v=4",
          "events_url": "https://api.github.com/users/reviewpad/events{/privacy}",
          "followers_url": "https://api.github.com/users/reviewpad/followers",
          "following_url": "https://api.github.com/users/reviewpad/following{/other_user}",
          "gists_url": "https://api.github.com/users/reviewpad/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/reviewpad",
          "id": 77885052,
          "login": "reviewpad",
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjc3ODg1MDUy",
          "organizations_url": "https://api.github.com/users/reviewpad/orgs",
          "received_events_url": "https://api.github.com/users/reviewpad/received_events",
          "repos_url": "https://api.github.com/users/reviewpad/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/reviewpad/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/reviewpad/subscriptions",
          "type": "Organization",
          "url": "https://api.github.com/users/reviewpad"
        },
        "private": false,
        "pulls_url": "https://api.github.com/repos/reviewpad/reviewpad/pulls{/number}",
        "releases_url": "https://api.github.com/repos/reviewpad/reviewpad/releases{/id}",
        "stargazers_url": "https://api.github.com/repos/reviewpad/reviewpad/stargazers",
        "statuses_url": "https://api.github.com/repos/reviewpad/reviewpad/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/reviewpad/reviewpad/subscribers",
        "subscription_url": "https://api.github.com/repos/reviewpad/reviewpad/subscription",
        "tags_url": "https://api.github.com/repos/reviewpad/reviewpad/tags",
        "teams_url": "https://api.github.com/repos/reviewpad/reviewpad/teams",
        "trees_url": "https://api.github.com/repos/reviewpad/reviewpad/git/trees{/sha}",
        "url": "https://api.github.com/repos/reviewpad/reviewpad"
      },
      "rerun_url": "https://api.github.com/repos/reviewpad/reviewpad/actions/runs/2705801670/rerun",
      "run_attempt": 1,
      "run_number": 437,
      "run_started_at": "2022-07-20T15:22:02Z",
      "status": "completed",
      "triggering_actor": {
        "avatar_url": "https://avatars.githubusercontent.com/u/601882?v=4",
        "events_url": "https://api.github.com/users/marcelosousa/events{/privacy}",
        "followers_url": "https://api.github.com/users/marcelosousa/followers",
        "following_url": "https://api.github.com/users/marcelosousa/following{/other_user}",
        "gists_url": "https://api.github.com/users/marcelosousa/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/marcelosousa",
        "id": 601882,
        "login": "marcelosousa",
        "node_id": "MDQ6VXNlcjYwMTg4Mg==",
        "organizations_url": "https://api.github.com/users/marcelosousa/orgs",
        "received_events_url": "https://api.github.com/users/marcelosousa/received_events",
        "repos_url": "https://api.github.com/users/marcelosousa/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/marcelosousa/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marcelosousa/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/marcelosousa"
      },
      "updated_at": "2022-07-20T15:22:47Z",
      "url": "https://api.github.com/repos/reviewpad/reviewpad/actions/runs/2705801670",
      "workflow_id": 29778599,
      "workflow_url": "https://api.github.com/repos/reviewpad/reviewpad/actions/workflows/29778599"
    }
  }
}`
