name: Build

on:
  pull_request:
  push:
    tags:
      - '**'

env:
  LD_LIBRARY_PATH: /usr/local/lib
  INPUT_SEMANTIC_SERVICE: 0.0.0.0:3006
  INPUT_ROBIN_SERVICE: 0.0.0.0:3011

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: reviewpad/ci:latest
    steps:
      - name: Set up git config
        run: git config --global url."https://${{ secrets.REVIEWPAD_TOKEN }}:@github.com/".insteadOf "https://github.com/"

      - uses: actions/checkout@v3

      - name: Download dependencies
        run: |
          go install golang.org/x/tools/cmd/goyacc@latest
          go install gotest.tools/gotestsum@latest
          go install github.com/jandelgado/gcov2lcov@latest
          go install github.com/go-task/task/v3/cmd/task@latest
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest

      - name: Check
        run: |
          task format
          task shadow

      - name: Build
        run: task build

      - name: Unit tests
        run: task test

      - name: Convert coverage to lcov
        run: gcov2lcov -infile=coverage.out -outfile=coverage.lcov

      - name: Verify that minimum coverage is covered
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "coverage.lcov"
          min_coverage: 70

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run codehost service
        run: |
          docker pull 766192842184.dkr.ecr.eu-central-1.amazonaws.com/codeatlas/hostsservice:latest
          docker run -p 9000:9000 -d 766192842184.dkr.ecr.eu-central-1.amazonaws.com/codeatlas/hostsservice:latest

      - name: Integration tests
        run: task integration-test
        env:
          GITHUB_INTEGRATION_TEST_TOKEN: ${{ secrets.REVIEWPAD_INTEGRATION_TESTS_TOKEN }}
          GITHUB_INTEGRATION_TEST_REPO_OWNER: reviewpad
          GITHUB_INTEGRATION_TEST_REPO_NAME: reviewpad-integration-test
          INPUT_CODEHOST_SERVICE: localhost:9000
