on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.repos.listCollaborators({owner: 'reviewpad', repo: 'reviewpad'})
            console.log(result)
