name: Pull Request Build

on:
  pull_request:
#    types: [ labeled, synchronize ]

env:
  LD_LIBRARY_PATH: /usr/local/lib
  INPUT_SEMANTIC_SERVICE: 0.0.0.0:3006

jobs:
  pr-build:
 #   if: ${{ (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'run-build')) || (github.event.action == 'labeled' && github.event.label.name == 'run-build') }}
    runs-on: ubuntu-latest
    container:
      image: reviewpad/ci:latest
    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        run: |
          go install golang.org/x/tools/cmd/goyacc@latest
          go install gotest.tools/gotestsum@latest
          go install github.com/jandelgado/gcov2lcov@latest
          go install github.com/go-task/task/v3/cmd/task@latest
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest

      - name: Check
        run: |
          task format
          task shadow

      - name: Build
        run: task build

      - name: Test
        run: task test

      - name: Convert coverage to lcov
        run: gcov2lcov -infile=coverage.out -outfile=coverage.lcov

      - name: Verify that minimum coverage is covered
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "coverage.lcov"
          min_coverage: 80
