# Copyright 2022 Explore.dev Unipessoal Lda. All Rights Reserved.
# Use of this source code is governed by a license that can be
# found in the LICENSE file.

name: Scheduled Tasks

# Close Issues and Pull Requests
# Check for Git Conflicts

on:
  schedule:
    # Run every day at midnight
    - cron: "0 0 * * *"

jobs:
  reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
        with:
          file: scheduled_tasks.yml
          token: ${{ secrets.REVIEWPAD_TOKEN }}
